CREATE TABLE TOL_OPTIONS (
       ID NUMERIC(4,0) NOT NULL
     , NOMBRE VARCHAR(100) NOT NULL
     , JERARQUI NUMERIC(4,0) DEFAULT 0 NOT NULL
     , ORDEN NUMERIC(4,0) NOT NULL
     , TIPO NUMERIC(4,0) NOT NULL
     , ES_MENU NUMERIC(4,0) NOT NULL
     , DESCRIP VARCHAR(250)
);

CREATE TABLE TOL_USUARIO (
       ID NUMERIC(4,0) NOT NULL
     , LOGIN VARCHAR(20) NOT NULL
     , NOMBRE VARCHAR(40) NOT NULL
     , APELLIDO VARCHAR(40) NOT NULL
     , ESTADO VARCHAR(1) NOT NULL
     , INGRDATE DATE NOT NULL
     , PASSWORD VARCHAR(40)
     , EMAIL VARCHAR(80)
     , RETIDATE DATE
);

CREATE TABLE INDICES (
       NOMBRE VARCHAR(50) NOT NULL
     , VALOR NUMERIC(10,0) NOT NULL
);

CREATE TABLE TOL_PCONFIG (
       ID NUMERIC(4,0) NOT NULL
     , NOMBRE VARCHAR(40) NOT NULL
     , VALOR NUMERIC(4,0)
     , DESCRIP VARCHAR(256)
);

CREATE TABLE TOL_PERFIL (
       ID NUMERIC(4,0) NOT NULL
     , NOMBRE VARCHAR(40) NOT NULL
     , DESCRIP VARCHAR(80)
);

CREATE TABLE TOL_OPTSXPRF (
       ID NUMERIC(4,0) NOT NULL
     , ID_PERF NUMERIC(4,0) NOT NULL
     , ID_OPTS NUMERIC(4,0) NOT NULL
);

CREATE TABLE TOL_PRFLXUSR (
       ID NUMERIC(4,0) NOT NULL
     , ID_PERFIL NUMERIC(4,0) NOT NULL
     , ID_USR NUMERIC(4,0) NOT NULL
);

CREATE TABLE TOL_MENSAJES(
	 ID NUMERIC(4, 0) NOT NULL,
   MODULO VARCHAR(100),
   MENSAJE VARCHAR(200),
   ID_AREA NUMERIC(4, 0)
   )
;

CREATE TABLE TOL_MENSXPRF (
	ID NUMERIC (4,0) NOT NULL,
	ID_PERF NUMERIC (4,0),
	ID_AREA NUMERIC (4,0)
	)
;

CREATE TABLE TOL_LOG_OPTS (
	ID NUMERIC (4,0 ) NOT NULL,
	ID_USR NUMERIC ( 4,0 ),
	ID_OPTS NUMERIC ( 4,0 ),
	TIME DATE,
	DESCRIP VARCHAR ( 500 )
	)
;

ALTER TABLE TOL_MENSAJES
  ADD CONSTRAINT PK_MENSAJES
      PRIMARY KEY (ID);

ALTER TABLE TOL_OPTIONS
  ADD CONSTRAINT PK_OPTIONS
      PRIMARY KEY (ID);

ALTER TABLE TOL_USUARIO
  ADD CONSTRAINT PK_USUARIO
      PRIMARY KEY (ID);

ALTER TABLE INDICES
  ADD CONSTRAINT PK_INDICES
      PRIMARY KEY (NOMBRE);

ALTER TABLE TOL_PCONFIG
  ADD CONSTRAINT PK_PCONFIG
      PRIMARY KEY (ID);

ALTER TABLE TOL_PERFIL
  ADD CONSTRAINT PK_PERFIL
      PRIMARY KEY (ID);

ALTER TABLE TOL_OPTSXPRF
  ADD CONSTRAINT PK_OPTSXPRF
      PRIMARY KEY (ID);

ALTER TABLE TOL_PRFLXUSR
  ADD CONSTRAINT PK_PRFLXUSR
      PRIMARY KEY (ID);

ALTER TABLE TOL_OPTSXPRF
  ADD CONSTRAINT FK_OPTSXPRF_1
      FOREIGN KEY (ID_PERF)
      REFERENCES TOL_PERFIL (ID);

ALTER TABLE TOL_OPTSXPRF
  ADD CONSTRAINT FK_OPTSXPRF_2
      FOREIGN KEY (ID_OPTS)
      REFERENCES TOL_OPTIONS (ID);

ALTER TABLE TOL_PRFLXUSR
  ADD CONSTRAINT FK_PRFLXUSR_1
      FOREIGN KEY (ID_PERFIL)
      REFERENCES TOL_PERFIL (ID);

ALTER TABLE TOL_PRFLXUSR
  ADD CONSTRAINT FK_PRFLXUSR_2
      FOREIGN KEY (ID_USR)
      REFERENCES TOL_USUARIO (ID);
      
ALTER TABLE TOL_MENSXPRF
	ADD CONSTRAINT PK_TOL_MENXP PRIMARY KEY (
		ID
		)
;

ALTER TABLE TOL_MENSXPRF
	ADD CONSTRAINT FK_TOLMEN 
		FOREIGN KEY (ID_AREA)
		REFERENCES TOL_MENSAJES (ID);

ALTER TABLE TOL_MENSXPRF
		ADD CONSTRAINT FK_PERF 
		FOREIGN KEY (ID_PERF)
	REFERENCES TOL_PERFIL (ID);

ALTER TABLE TOL_LOG_OPTS
	ADD CONSTRAINT PK_TOLLOGOP PRIMARY KEY (
		ID
		)
;