--INDICES
--INSERT INTO SHOPPING.INDICES (NOMBRE, VALOR) VALUES ('SEQ_IDIOMA', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_LOG_OPTS', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_LOG_REP', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_LOG_PROP', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_USUARIO', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_PERFIL', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_OPTSXPRF', 33);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_PRFLXUSR', 1);
INSERT INTO INDICES (NOMBRE, VALOR) VALUES ('SEQ_TOL_MENSXPRF', 2);

--MENSAJES
INSERT INTO TOL_MENSAJES (ID, MODULO, MENSAJE, ID_AREA) VALUES (1, 'Administración', 'Bienvenido al módulo de administración.', 448);

--TOL_OPTIONS
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (448, 'Administración', 0, 2, 1, 1, 'Entrada a perfil de Administración');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (449, 'Administración de usuarios', 448, 1, 2, 1, 'Entrada a menú de Administración de usuarios');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (456, 'Usuarios', 449, 1, 2, 1, 'Entrada al menú de Usuarios');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (457, 'Administración', 456, 1, 2, 1, 'Entrada Menú de Administración');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (458, 'Crear Usuarios', 457, 0, 3, 0, 'Crear usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (459, 'Asociar Perfil a usuario', 458, 0, 3, 0, 'Asociar Perfil a Usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (460, 'Editar Usuarios', 457, 0, 3, 0, 'Editar usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (461, 'Eliminar Usuarios', 457, 0, 3, 0, 'Eliminar usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (462, 'Buscar Usuarios', 457, 0, 3, 0, 'Buscar usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (463, 'Cambiar Estado a Usuario', 456, 2, 2, 1, 'Entrada a menú Cambiar estado usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (464, 'Estado Usuarios', 463, 0, 3, 0, 'Cambiar estado usuario');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (471, 'Perfiles', 449, 2, 2, 1, 'Entrada al menú de Perfiles');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (472, 'Crear Perfiles', 471, 0, 3, 0, 'Crear Perfil');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (473, 'Editar Perfiles', 471, 0, 3, 0, 'Editar Perfil');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (474, 'Eliminar Perfiles', 471, 0, 3, 0, 'Eliminar Perfil');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (475, 'Listar Perfiles', 471, 0, 3, 0, 'Listar Perfiles');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (476, 'Asociar perfil a funcionalidad', 472, 0, 3, 0, 'Asociar perfil a funcionalidad');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (483, 'Log de Acciones', 449, 3, 2, 1, 'Entrada Menú Consultar log de Acciones');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (484, 'Consultar Log de Acciones', 483, 0, 3, 0, 'Consultar log de Acciones');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (490, 'Log de Reportes', 449, 4, 2, 1, 'Menú Consultar log de reportes');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (491, 'Consultar Log de Reportes', 490, 0, 3, 0, 'Consultar log de Reportes');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (542, 'Conexión de BD relacional', 448, 4, 2, 1, 'Consultar conexión de BD relacional');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (543, 'Editar Conexión de BD relacional', 542, 0, 3, 0, 'Editar conexión de BD relacional');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (550, 'Mensajes de Bienvenida', 448, 5, 2, 1, 'Entrada a menú Mensajes de Bienvenida');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (551, 'Editar Mensaje de Bienvenida', 550, 0, 3, 0, 'Editar Mensaje de Bienvenida');
INSERT INTO TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (608, 'Cambiar Contraseña', 448, 8, 2, 1, 'Entrada a menú Cambiar contraseña por administrador');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (700, 'Parámetros generales', 0, 3, 2, 1, 'Ingreso a parametros generales');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (710, 'Crear Idioma', 700, 7, 3, 0, 'Crear idioma');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (711, 'Actualizar Idioma', 700, 8, 3, 0, 'Actualizar idioma');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (712, 'Eliminar Idioma', 700, 9, 3, 0, 'Eliminar idioma');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (713, 'Ingreso a Diccionario', 700, 10, 3, 0, 'Ingreso a diccionario');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (714, 'Crear Expresion', 700, 11, 3, 0, 'Crear expresion');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (715, 'Actualizar expresion', 700, 12, 3, 0, 'Actualizar expresion');
--INSERT INTO TXONLINE.TOL_OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP) VALUES (716, 'Eliminar expresion', 700, 13, 3, 0, 'Eliminar expresion');
