--PERFIL
INSERT INTO TOL_PERFIL (ID, NOMBRE, DESCRIP) VALUES (1, 'Admin', 'Administrador del Sistema');

--TOL_OPTSXPRF
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (1, 448, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (2, 449, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (3, 456, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (4, 457, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (5, 458, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (6, 459, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (7, 460, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (8, 461, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (9, 462, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (10, 463, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (11, 464, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (12, 471, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (13, 472, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (14, 473, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (15, 474, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (16, 475, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (17, 476, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (18, 483, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (19, 484, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (20, 542, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (21, 543, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (22, 550, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (23, 551, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (24, 608, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (25, 700, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (26, 710, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (27, 711, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (28, 712, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (29, 713, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (30, 714, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (31, 715, 1);
--INSERT INTO TXONLINE.TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (32, 716, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (25, 490, 1);
INSERT INTO TOL_OPTSXPRF (ID, ID_OPTS, ID_PERF) VALUES (26, 491, 1);

--TOL_PCONFIG
INSERT INTO TOL_PCONFIG (ID, NOMBRE, VALOR, DESCRIP) VALUES (1, 'INTENTOS_LOGIN', 3, 'INTENTOS FALLIDOS DE LOGIN PERMITIDOS');

--USUARIO
INSERT INTO TOL_USUARIO (ID, LOGIN, PASSWORD, NOMBRE, APELLIDO, EMAIL, ESTADO, INGRDATE, RETIDATE) VALUES (1, 'admin', 'NWoZK3kTsExUV00Ywo1G5jlUKKs=', 'Admin', 'Admin', 'admin.admin@asicamericas.com', 'A', CURRENT DATE, NULL);

--PRFLXUSR
INSERT INTO TOL_PRFLXUSR (ID, ID_USR, ID_PERFIL) VALUES (1, 1, 1);

--IDIOMA
--INSERT INTO TXONLINE.IDIOMA VALUES(1, 'ESPAÑOL');
