ALTER TABLE TPOS_ITEMENTRY ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_HEADER ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;

ALTER TABLE TPOS_DATA_ENTRY ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_DISCOUNT ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_EXCEPTION_LOG ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_ITEM_RECORD_CHANGE ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_MANAGER_OVERRIDE ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_OPERATOR_TRAINING ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_PRICE_CHANGE ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_TAX ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_TENDER ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_TENDER ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_TILL_CHANGE ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_TRADING_STAMPS ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_USER_DATA ADD COLUMN FECHAHORA TIMESTAMP;
ALTER TABLE TPOS_STORE_CLOSING ADD COLUMN TFECHAHORA TIMESTAMP;


ALTER TABLE TPOS_ITEMENTRY ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_HEADER ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_DATA_ENTRY ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_DISCOUNT ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_EXCEPTION_LOG ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_ITEM_RECORD_CHANGE ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_MANAGER_OVERRIDE ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_OPERATOR_TRAINING ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_PRICE_CHANGE ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_TAX ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_TENDER ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_TENDER ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_TILL_CHANGE ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_TRADING_STAMPS ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_USER_DATA ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;
ALTER TABLE TPOS_STORE_CLOSING ADD COLUMN INFECHAHORA TIMESTAMP NOT NULL  WITH DEFAULT CURRENT TIMESTAMP;

ALTER TABLE TOL_SUPPORT_STORE ADD COLUMN TOL_EXEC CHAR(1) NOT NULL  WITH DEFAULT '1';

// 21 Feb 2023 Adición de columnas a ItemEntry para factura electrónica
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN impconrate NUMERIC(3);
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN unidmedida VARCHAR(3); 
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN descuento NUMERIC(10);

// 26 Feb 2023 Adición de columnas a ItemEntry para Inventarios en línea
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN vatbaseamt NUMERIC(10);
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN vattaxamt NUMERIC(10);

# 26 Octubre 2023 FACTURA ELECTRONICA ICUI
ALTER TABLE TPOS_ITEMENTRY ADD COLUMN ICUITAXRATE NUMERIC(3);



