DROP TABLE ORGMSTEE;

CREATE TABLE ORGMSTEE(
	ORG_LVL_CHILD NUMBER(12),   
	ORG_LVL_PARENT NUMBER(12), 
	ORG_LVL_ID NUMBER(5),
	ORG_NAME_FULL VARCHAR2(50),
	ORG_NAME_SHORT VARCHAR2(8),
	ORG_LVL_NUMBER NUMBER(12),
	CURR_CODE CHAR(3),
	ORG_IS_STORE CHAR(1)
);
