
CREATE TABLE  TOL_SUPPORT_STORE (
TOL_ID		INTEGER NOT NULL,
TOL_NAME 	CHAR(40)
);

ALTER TABLE TOL_SUPPORT_STORE ADD CONSTRAINT "PK_TOL_SUPPORT_STORE" PRIMARY KEY (TOL_ID);

CREATE TABLE TOL_STORE_CONCILIATION (
TSC_STORE_ID		INTEGER NOT NULL,
TSC_GROSS_SALES     NUMERIC(10)NOT NULL, // Ventas brutas calculados con el gross positive desde la tabla TPOS_HEADER
TSC_VOIDED_ITEMS	NUMERIC(10)NOT NULL, // Anulaciones (de productos)calculadas desde la tabla TPOS_ITEMENTRY
TSC_REFUNDED_ITEMS	NUMERIC(10)NOT NULL, // Devoluciones (de productos)calculadas desde la tabla TPOS_ITEMENTRY
TSC_TOTAL_DISCOUNTS NUMERIC(10)NOT NULL, // Descuentos desde la tabla TPOS_DISCOUNT
TSC_MISCELLA_AMOUNT NUMERIC(10)NOT NULL, // Monto de artículos miscelaneos vendidos desde la tabla TPOS_ITEMENTRY
TSC_VOIDED_TRXS_AMT NUMERIC(10)NOT NULL, // Monto de trxs anuladas desde la tabla TPOS_HEADER
TSC_ITM_GROSS_POSIT NUMERIC(10)NOT NULL, // Gross positivo desde la tabla TPOS_ITEMENTRY 
TSC_ITM_GROSS_NEGAT NUMERIC(10)NOT NULL, // Gross negativo desde la tabla TPOS_HEADER
TSC_CUST_TICKET_NUM NUMERIC(8)NOT NULL, // Customers o tickets number desde la tabla TPOS_HEADER
TSC_STORE_COUPONS   NUMERIC(8)NOT NULL, // Número de store coupons en el período desde la tabla TPOS_ITEMENTRY
TSC_ITEMS_SOLDS_NUM NUMERIC(10)NOT NULL, // No total de ítems vendidos de ítems vendidos desde la tabla TPOS_ITEMENTRY
TSC_FECHAHORA_INI TIMESTAMP NOT NULL, // Fecha inicial período
TSC_FECHAHORA_FIN TIMESTAMP NOT NULL, // Fecha final período
TSC_INFECHAHORA TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP // Fecha inserción en tabla
);

ALTER TABLE TOL_STORE_CONCILIATION ADD CONSTRAINT "PK_TOL_STORE_CONCILIATION" PRIMARY KEY (TSC_STORE_ID,TSC_FECHAHORA_INI,TSC_FECHAHORA_FIN);