alter table TX_RECHAZO modify  ( ERROR varchar( 4003 ) );

ALTER TABLE TPOS_USER_DATA ADD TIPO VARCHAR2(1);

select * from TPOS_HEADER where DAY =TIMESTAMP  '2006-01-16 12:00:00';

CREATE INDEX tpos_header_ind ON TPOS_HEADER (DAY, STORE, OFFSETY,OFFSETX,TERMINAL,TRANSNUM, TIPO);

SELECT TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY') day  FROM dual;