--CONNECT TO TRX_LINEA;
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_LOG_OPTS',1 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_LOG_REP',5 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_LOG_PROP',1 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_USUARIO',6 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_PERFIL',5 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_OPTSXPRF',45 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_PRFLXUSR',11 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_MENSXPRF',4 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_AUDIT',1 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_DETSERV',1 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_MENSAJE',4 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_PCONFIG',1 );
INSERT INTO INDICES (NOMBRE, VALOR)  VALUES ( 'SEQ_SERVICIO',1 );

INSERT INTO MENSAJES (ID, MODULO, MENSAJE, ID_AREA)  VALUES ( 1,'Administración','Módulo de administración',448 );
INSERT INTO MENSAJES (ID, MODULO, MENSAJE, ID_AREA)  VALUES ( 2,'Administración de contenidos','Módulo de administración de contenidos',750 );
INSERT INTO MENSAJES (ID, MODULO, MENSAJE, ID_AREA)  VALUES ( 3,'Administración de portlets','Módulo de administración de portlets',650 );

INSERT INTO PERFIL (ID, NOMBRE, DESCRIP)  VALUES ( 1,'Admin','Administrador del Sistema' );
INSERT INTO PERFIL (ID, NOMBRE, DESCRIP)  VALUES ( 2,'guest','Perfil de usuarios anonimos' );
INSERT INTO PERFIL (ID, NOMBRE, DESCRIP)  VALUES ( 3,'adminportal','Administración de portal' );
INSERT INTO PERFIL (ID, NOMBRE, DESCRIP)  VALUES ( 4,'adminContenidos','Administración de contenidos' );


INSERT INTO MENSXPRF (ID, ID_PERF, ID_AREA)  VALUES ( 1,1,1 );
INSERT INTO MENSXPRF (ID, ID_PERF, ID_AREA)  VALUES ( 2,4,2 );
INSERT INTO MENSXPRF (ID, ID_PERF, ID_AREA)  VALUES ( 3,3,3 );

INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 448,'Administración',0,3,1,1,'Entrada a perfíl de Administración' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 449,'Administración de Usuarios',448,1,2,1,'Entrada a menú de Administración de Usuarios' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 456,'Usuarios',449,1,2,1,'Entrada al menú Usuarios' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 457,'Administración',456,1,2,1,'Entrada al menú Administración' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 458,'Crear Usuarios',457,0,3,0,'Crear usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 459,'Asociar Perfil a usuario',458,0,3,0,'Asociar Perfil a Usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 460,'Editar Usuarios',457,0,3,0,'Editar usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 461,'Eliminar Usuarios',457,0,3,0,'Eliminar usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 462,'Buscar Usuarios',457,0,3,0,'Buscar usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 463,'Cambiar Estado a Usuario',449,2,2,1,'Entrada a menú Cambiar estado usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 464,'Estado Usuarios',463,0,3,0,'Cambiar estado usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 471,'Perfiles',449,2,2,1,'Entrada a menú Perfiles' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 472,'Crear Perfiles',471,0,3,0,'Crear Perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 473,'Editar Perfiles',471,0,3,0,'Editar Perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 474,'Eliminar Perfiles',471,0,3,0,'Eliminar Perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 475,'Listar Perfiles',471,0,3,0,'Listar Perfiles' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 476,'Asociar perfil a funcionalidad',472,0,3,0,'Asociar perfil a funcionalidad' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 483,'Log de Acciones',449,3,2,1,'Entrada Menú Consultar log de Acciones' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 484,'Consultar Log de Acciones',483,0,3,0,'Consultar log de Acciones' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 542,'Conexión de BD Relacional',448,2,2,1,'Consultar Conexión de BD Relacional' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 543,'Editar Conexión de BD Relacional',542,0,3,0,'Editar Conexión de BD Relacional' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 550,'Mensajes de Bienvenida',448,3,2,1,'Entrada a menú Mensajes de Bienvenida' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 551,'Editar Mensaje de Bienvenida',550,0,3,0,'Editar Mensaje de Bienvenida' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 608,'Cambiar Contraseña',448,4,2,1,'Entrada a Menú Cambiar Contraseña por administrador' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 650,'Administración de Portlets',448,3,2,1,'Administración de Portlets' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 660,'Administración de Páginas',650,1,4,1,'Administración de Páginas' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 680,'Administración de Instancias',650,2,3,1,'Administración de Instancias' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 690,'Administración de Categorías',650,4,2,1,'Administración de Portlets' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 720,'Administración de Carpetas',448,3,3,1,'Administración de Carpetas' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 750,'Administrar contenidos',448,6,2,1,'Administrar contenidos' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 730,'Administrar permisos de páginas por perfil',650,5,3,1,'Administrar permisos de páginas por perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 740,'Administrar permisos de instancias por perfil',650,6,3,1,'Administrar permisos de instancias por perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 721,'Administración de raíces',720,1,3,1,'Administración de raíces' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 722,'Administración de carpetas',720,2,3,1,'Administración de carpetas' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 723,'Administración de permisos de carpeta por perfil',720,3,3,1,'Administración de permisos de carpeta por perfil' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 724,'Administración de permisos de carpetas por usuario',720,4,3,1,'Administración de permisos de carpetas por usuario' );
INSERT INTO OPTIONS (ID, NOMBRE, JERARQUI, ORDEN, TIPO, ES_MENU, DESCRIP)  VALUES ( 616, 'Cambiar Contraseña', 448, 0, 3, 0, 'Cambiar Contraseña' );

INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 1,1,448 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 2,1,449 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 3,1,456 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 4,1,457 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 5,1,458 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 6,1,459 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 7,1,460 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 8,1,461 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 9,1,462 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 10,1,463 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 11,1,464 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 12,1,471 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 13,1,472 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 14,1,473 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 15,1,474 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 16,1,475 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 17,1,476 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 18,1,483 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 19,1,484 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 25,1,542 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 26,1,543 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 27,1,550 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 28,1,551 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 29,1,608 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 21,1,616 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 30,4,448 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 31,4,750 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 38,3,448 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 39,3,650 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 40,3,660 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 41,3,680 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 42,3,720 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 43,3,690 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 44,3,730 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 45,3,740 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 46,3,720 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 47,3,721 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 48,3,722 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 49,3,723 );
INSERT INTO OPTSXPRF (ID, ID_PERF, ID_OPTS)  VALUES ( 50,3,724 );

INSERT INTO USUARIO  VALUES ( 0,'admin','sMhI1g8cqO91zpAIgG/Io0LkI8o=','admin','admin','admin@sistema.com.co','A',sysdate,null);
INSERT INTO USUARIO  VALUES ( 1,'test','qUqP5cyxm6YcTAhz05Hph5gvu9M=','test','test','test@test.com','A',sysdate,null );
INSERT INTO USUARIO  VALUES ( 2,'guest','sMhI1g8cqO91zpAIgG/Io0LkI8o=','guest','guest','guest@sistema.com.co','A',sysdate,null);
INSERT INTO USUARIO  VALUES ( 4,'adminportal','a9ZNUblKIU93Ua6Sljy/KD7EqRs=','adminportal','adminportal','adminportal@asicamericas.com','A',sysdate,null);
INSERT INTO USUARIO  VALUES ( 5,'admincont','orZzsT65eKVkznT5x2NQEp5CbJU=','admincont','admincont','admincont@asicamericas.com','A',sysdate,null);

INSERT INTO USUARIO  VALUES ( 0,'admin','sMhI1g8cqO91zpAIgG/Io0LkI8o=','admin','admin','admin@sistema.com.co','A', CURRENT DATE,null);
INSERT INTO USUARIO  VALUES ( 1,'test','qUqP5cyxm6YcTAhz05Hph5gvu9M=','test','test','test@test.com','A',CURRENT DATE,null );
INSERT INTO USUARIO  VALUES ( 2,'guest','sMhI1g8cqO91zpAIgG/Io0LkI8o=','guest','guest','guest@sistema.com.co','A',CURRENT DATE,null);
INSERT INTO USUARIO  VALUES ( 4,'adminportal','a9ZNUblKIU93Ua6Sljy/KD7EqRs=','adminportal','adminportal','adminportal@asicamericas.com','A',CURRENT DATE,null);
INSERT INTO USUARIO  VALUES ( 5,'admincont','orZzsT65eKVkznT5x2NQEp5CbJU=','admincont','admincont','admincont@asicamericas.com','A',CURRENT DATE,null);



INSERT INTO PRFLXUSR (ID, ID_USR, ID_PERFIL)  VALUES ( 1,0,1 );
INSERT INTO PRFLXUSR (ID, ID_USR, ID_PERFIL)  VALUES ( 2,2,2 );
INSERT INTO PRFLXUSR (ID, ID_USR, ID_PERFIL)  VALUES ( 8,4,3 );
INSERT INTO PRFLXUSR (ID, ID_USR, ID_PERFIL)  VALUES ( 9,5,4 );


INSERT INTO PCONFIG VALUES (1, 'Intentos_login', 3, 'Intentos de logeo');
--commit;
--connect reset;
